# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.toml', '.'),
        ('simbizmall-5717f-firebase-adminsdk-45is2-597a4fbefc.json', '.'),
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'tkinter',
        'scheduler',
        'pymongo',
        'firebase_admin',
        'firebase_admin._utils',
        'firebase_admin.credentials',
        'firebase_admin.firestore',
        'google.cloud.firestore_v1',
        'grpc',
        'google.api_core',
        'google.auth',
        'requests',
        'toml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='KDNavien_Middleware',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets\\icons\\KDNAVIEN.ico'],
)